-- local vim = _G.vim -- Let lua lsp know that vim is global
-- This config works, but overlapping nvim-cmp and virtualtext is annoying
--  require('minuet').setup {
--    virtualtext = {
--      auto_trigger_ft = {}, --  filetypes for auto-completion
--      keymap = {
--        accept = '<C-k>',
--        accept_line = '<C-l>',
--        accept_n_lines = nil,
--        prev = '<C-t>',
--        next = '<C-g>',
--        dismiss = '<C-q>',
--      },
--      show_on_completion_menu = false
--    },
--    provider = 'gemini',
--    context_window = 768,
--    request_timeout = 10,
--    notify = "debug",
--    provider_options = {
--      gemini = {
--        api_key = "GEMINI_API_KEY",
--      }
--    },
--    lsp = {
--      enable_auto_trigger = true
--    }
--  }
--  vim.keymap.set("n", "<leader>mi", "<cmd>Minuet virtualtext toggle<CR>", { desc = "Minuet Complete" })
--end
